# Generated by Django 3.2.4 on 2022-03-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingbatch",
            name="shipping_transport",
            field=models.ForeignKey(
                blank=True,
                help_text="assigned to single transport",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.shippingtransport",
            ),
        ),
    ]
