# Generated by Django 3.2.4 on 2022-03-08 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistributionCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("center_code", models.CharField(db_index=True, max_length=16)),
                ("name", models.CharField(db_index=True, max_length=64)),
                (
                    "staff_members",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'uuid': ['uuid','uuid']}",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "distribution_distribution_center",
            },
        ),
    ]
