# Generated by Django 3.2.4 on 2022-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncenter',
            name='center_code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
